-- MySQL Script generated by MySQL Workbench
-- Wed Jun 20 22:30:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbclase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbclase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbclase` DEFAULT CHARACTER SET utf8 ;
USE `dbclase` ;

-- -----------------------------------------------------
-- Table `dbclase`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclase`.`distrito` (
  `iddistrito` INT(45) NOT NULL AUTO_INCREMENT,
  `distrito` VARCHAR(45) NULL,
  PRIMARY KEY (`iddistrito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbclase`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbclase`.`cliente` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `paterno` VARCHAR(45) NULL,
  `materno` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT(9) NULL,
  `iddistrito` INT(45) NULL,
  `correo` VARCHAR(45) NULL,
  `imagen` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo`),
  INDEX `name_distrito_idx` (`iddistrito` ASC),
  CONSTRAINT `name_distrito`
    FOREIGN KEY (`iddistrito`)
    REFERENCES `dbclase`.`distrito` (`iddistrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
